"""Add dob, id number and baptismref to user model

Revision ID: 19148b40e9a5
Revises: 2a996a43d731
Create Date: 2025-08-05 12:40:31.751694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19148b40e9a5'
down_revision: Union[str, Sequence[str], None] = '2a996a43d731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dateofbirth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('idnumber', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('baptismref', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['idnumber'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'baptismref')
    op.drop_column('users', 'idnumber')
    op.drop_column('users', 'dateofbirth')
    # ### end Alembic commands ###
