"""add outstations table

Revision ID: 2a1549377f04
Revises: 26c4bd4788cc
Create Date: 2025-07-02 16:18:53.928194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1549377f04'
down_revision: Union[str, Sequence[str], None] = '26c4bd4788cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_outstations_id'), 'outstations', ['id'], unique=False)
    op.create_index(op.f('ix_outstations_name'), 'outstations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outstations_name'), table_name='outstations')
    op.drop_index(op.f('ix_outstations_id'), table_name='outstations')
    op.create_index(op.f('idx_parish_id'), 'outstations', ['parish_id'], unique=False)
    op.create_index(op.f('idx_name'), 'outstations', ['name'], unique=False)
    # ### end Alembic commands ###
