"""remove deanery name from foreign key

Revision ID: 2a8c51bb9463
Revises: 4c2a6b19cd69
Create Date: 2025-07-08 12:34:39.146045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a8c51bb9463'
down_revision: Union[str, Sequence[str], None] = '4c2a6b19cd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('parishes_ibfk_2'), 'parishes', type_='foreignkey')
    op.drop_column('parishes', 'deanery_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parishes', sa.Column('deanery_name', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key(op.f('parishes_ibfk_2'), 'parishes', 'deaneries', ['deanery_name'], ['name'])
    op.create_index(op.f('idx_parish_id'), 'outstations', ['parish_id'], unique=False)
    # ### end Alembic commands ###
