"""Add prefix field to Deanery

Revision ID: 5b5a25b95c5d
Revises: d1c5b5c54299
Create Date: 2025-10-22 13:51:35.747764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5a25b95c5d'
down_revision: Union[str, Sequence[str], None] = 'd1c5b5c54299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deaneries', sa.Column('prefix', sa.String(length=6), nullable=True))
    op.create_unique_constraint(None, 'deaneries', ['prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deaneries', type_='unique')
    op.drop_column('deaneries', 'prefix')
    # ### end Alembic commands ###
