"""add user role in user model

Revision ID: 603bf2638928
Revises: 82fd19f17a75
Create Date: 2025-07-01 10:19:03.981303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603bf2638928'
down_revision: Union[str, Sequence[str], None] = '82fd19f17a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('parish_member', 'parish_moderator', 'deanery_moderator', 'ysc_coordinator', 'ysc_chaplain', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
