"""Add prefix field to parish

Revision ID: 64d49b883bea
Revises: 5b5a25b95c5d
Create Date: 2025-10-22 16:52:22.596860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d49b883bea'
down_revision: Union[str, Sequence[str], None] = '5b5a25b95c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parishes', sa.Column('prefix', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parishes', 'prefix')
    # ### end Alembic commands ###
