"""Add outstation model and tweak relationships

Revision ID: 9d5a9c4a41b2
Revises: cfd7d3a96570
Create Date: 2025-07-02 14:24:19.061997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5a9c4a41b2'
down_revision: Union[str, Sequence[str], None] = 'cfd7d3a96570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deaneries_name'), 'deaneries', ['name'], unique=True)
    op.create_index(op.f('ix_parishes_name'), 'parishes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parishes_name'), table_name='parishes')
    op.drop_index(op.f('ix_deaneries_name'), table_name='deaneries')
    # ### end Alembic commands ###
