"""Create db

Revision ID: aae4cb111ef7
Revises: 
Create Date: 2025-09-10 13:00:15.750503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae4cb111ef7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=True)
    op.create_table('deaneries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deaneries_id'), 'deaneries', ['id'], unique=False)
    op.create_index(op.f('ix_deaneries_name'), 'deaneries', ['name'], unique=True)
    op.create_table('parishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('deanery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deanery_id'], ['deaneries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parishes_id'), 'parishes', ['id'], unique=False)
    op.create_index(op.f('ix_parishes_name'), 'parishes', ['name'], unique=False)
    op.create_table('outstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outstations_id'), 'outstations', ['id'], unique=False)
    op.create_index(op.f('ix_outstations_name'), 'outstations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phonenumber', sa.String(length=20), nullable=True),
    sa.Column('dateofbirth', sa.Date(), nullable=True),
    sa.Column('idnumber', sa.Integer(), nullable=True),
    sa.Column('baptismref', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('parish_member', 'parish_moderator', 'deanery_moderator', 'ysc_coordinator', 'ysc_chaplain', 'super_user', name='userrole'), nullable=True),
    sa.Column('status', sa.Enum('active_member', 'archived_member', 'transitioned_member', name='userstatus'), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('membership_no', sa.String(length=10), nullable=True),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idnumber')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outstations_name'), table_name='outstations')
    op.drop_index(op.f('ix_outstations_id'), table_name='outstations')
    op.drop_table('outstations')
    op.drop_index(op.f('ix_parishes_name'), table_name='parishes')
    op.drop_index(op.f('ix_parishes_id'), table_name='parishes')
    op.drop_table('parishes')
    op.drop_index(op.f('ix_deaneries_name'), table_name='deaneries')
    op.drop_index(op.f('ix_deaneries_id'), table_name='deaneries')
    op.drop_table('deaneries')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
