"""update revisions

Revision ID: bb16053086e4
Revises: 2a8c51bb9463
Create Date: 2025-07-10 15:47:06.760240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb16053086e4'
down_revision: Union[str, Sequence[str], None] = '2a8c51bb9463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_parish_id'), 'outstations', ['parish_id'], unique=False)
    # ### end Alembic commands ###
