"""create events-parish registraion table

Revision ID: bb4302950557
Revises: b7db653ce3d4
Create Date: 2026-03-20 09:47:51.645184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4302950557'
down_revision: Union[str, Sequence[str], None] = 'b7db653ce3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_parish_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('number_of_participants', sa.Integer(), nullable=False),
    sa.Column('is_cleared', sa.Boolean(), nullable=False),
    sa.Column('clearance_note', sa.Text(), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=False),
    sa.Column('cleared_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cleared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'parish_id', name='uq_event_parish_registration')
    )
    op.create_index(op.f('ix_event_parish_registrations_id'), 'event_parish_registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_parish_registrations_id'), table_name='event_parish_registrations')
    op.drop_table('event_parish_registrations')
    # ### end Alembic commands ###
