"""index membership no

Revision ID: db9c50fcbc1b
Revises: 04adb8b096e2
Create Date: 2025-10-22 17:17:45.627714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9c50fcbc1b'
down_revision: Union[str, Sequence[str], None] = '04adb8b096e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_membership_no'), 'users', ['membership_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_membership_no'), table_name='users')
    # ### end Alembic commands ###
