"""Change baptismref type

Revision ID: dc920580c72c
Revises: 19148b40e9a5
Create Date: 2025-08-05 12:42:47.649194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc920580c72c'
down_revision: Union[str, Sequence[str], None] = '19148b40e9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'baptismref',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'baptismref',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
