"""add roles and permissions tables

Revision ID: ffbfae9b4af3
Revises: 7db95a5200a8
Create Date: 2026-08-19 13:56:13.729485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbfae9b4af3'
down_revision: Union[str, Sequence[str], None] = '7db95a5200a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('role_has_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('model_has_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_foreign_key(None, 'event_parish_registrations', 'users', ['admitted_by'], ['id'])
    # ### end Alembic commands ###
    
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO roles (name, description, created_at)
        VALUES
            ('parish_member', NULL, NOW()),
            ('parish_moderator', NULL, NOW()),
            ('deanery_moderator', NULL, NOW()),
            ('ysc_coordinator', NULL, NOW()),
            ('ysc_chaplain', NULL, NOW()),
            ('super_user', NULL, NOW())
    """))

    users = connection.execute(sa.text("SELECT id, role FROM users WHERE role IS NOT NULL")).fetchall()
    roles = connection.execute(sa.text("SELECT id, name FROM roles")).fetchall()
    role_id_by_name = {r.name: r.id for r in roles}

    for user in users:
        role_id = role_id_by_name.get(user.role)
        if role_id:
            connection.execute(
                sa.text("INSERT INTO model_has_roles (role_id, user_id) VALUES (:role_id, :user_id)"),
                {"role_id": role_id, "user_id": user.id},
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_parish_registrations', type_='foreignkey')
    op.drop_table('model_has_roles')
    op.drop_table('role_has_permissions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
