name: Deploy to cPanel via FTP
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: adn-youth.org
          username: api_ftp@adn-youth.org
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /home1/adnyouth/python/main/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/venv/**
            **/__pycache__/**
            **/.env
            **/tests/**
            **/README.md
