name: Deploy to cPanel (SFTP)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: 1980
          
          TARGET: /home/${{ secrets.USERNAME }}/python/main
          EXCLUDE: "/node_modules/, /vendor/, .git/, .github/"
