name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: FTP Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: './'
        remote-dir: ${{ secrets.FTP_DIR }}

    - name: Trigger Python app restart
      run: echo "Touching passenger_wsgi.py to restart app"
